### ISSUE TITLE
rbenv_gem doesn't install gems

### ISSUE THREAD

**Issue by axsuul** [sous-chefs/ruby_rbenv#105]
``` ruby
include_recipe "rbenv::system_install"

version = "2.1.0"

# Install ruby and set it as global version
rbenv_ruby version
rbenv_global version

# Install gems
rbenv_gem "backup" do
  version "4.1.6"
  rbenv_version version
end
```

Running this recipe succeeds but doesn't actually install gem. Have tried this on many notable gems (i.e. `bundler`). Any thoughts?

**Comment by CloCkWeRX** [comment]
That usage should pretty much work right. Got any more detailed logs?

**Comment by hack2learn** [comment]
Same issue here. Even with specifying the user it seems it does install it but when you run gem list it is not listed at all. 

My workaround for now is this:

``` ruby
execute "install gem bundler" do
  command "runuser -l #{node["cme"]["user"]} -c \'gem install bundler\'"
end
```

the only downside is, that it gets executed everytime unless you add not_if with a block to check if the gem is already installed.
