### ISSUE TITLE
2.2.0 fails to build on Ubuntu 14.04.1

### ISSUE THREAD

**Issue by mcfiredrill** [sous-chefs/ruby_rbenv#106]
See the issue mentioned in rbenv:
https://github.com/sstephenson/ruby-build/issues/690

See the comment here:
https://github.com/sstephenson/ruby-build/issues/690#issuecomment-68113987

```
Please install libffi-dev via apt-get or use '--enabled-shared' option
```

Is it possible to add libffi-dev as a dependency to this cookbook or add the '--enabled-shared' option?

**Comment by tas50** [comment]
This actually occurs in the ruby-build cookbook.  You should file a bug against it instead.

https://github.com/fnichol/chef-ruby_build/blob/master/attributes/default.rb

**Comment by mcfiredrill** [comment]
@tas50 Thanks, I will file a bug there.
