### ISSUE TITLE
Help maintaining this repository

### ISSUE THREAD

**Issue by josegonzalez** [sous-chefs/ruby_rbenv#109]
It would be useful to the chef community that uses rbenv - us poor souls somehow managing rubby :( - to have an excellent rbenv cookbook. I think this one goes quite a long way, just needs a bit of love, and I'd be more than happy to help out.

I've helped clean up and continue maintenance on other projects - the most visible being revitalizing development on [dokku](https://github.com/progrium/dokku) - and thus think I have the track record to help get this back on track.

If you're willing/able, I'd love to have commit rights so I can start working on the backlog of issues and pull requests. Totally up to you though :)

**Comment by aried3r** [comment]
Love the idea! Think you can drop him a mail? @fnichol doesn't seem to look at this repo actively anymore.

**Comment by josegonzalez** [comment]
I messaged him on Twitter, I'll try to dig up his email later :)

**Comment by CloCkWeRX** [comment]
So; its been some time - I'm happy to add in collaborators into my fork or even turn it into an organization.  Who's interested?

**Comment by josegonzalez** [comment]
@CloCkWeRX mind making that an organization? I'm certainly interested in helping out if so :)

**Comment by CloCkWeRX** [comment]
Done and done: https://github.com/chef-rbenv/chef-rbenv

**Comment by CloCkWeRX** [comment]
@fnichol - try the transfer again, just deleted above repo.

**Comment by fnichol** [comment]
@CloCkWeRX Excellent, I think we're in business! :cake: :tada: :balloon:

**Comment by voelzmo** [comment]
@CloCkWeRX @fnichol Wow, now the repo is on the old state again? I just tried to `berks vendor` and it doesn't find the patched version 0.7.3 anymore. Was this intended?

**Comment by josegonzalez** [comment]
@voelzmo Please be patient while we make all the migration changes. I'd imagine @CloCkWeRX has a fulltime job and is working on this during his break ;)

**Comment by voelzmo** [comment]
@josegonzalez sure, I didn't mean to be ungrateful or demanding. I just wanted to make sure that this didn't happen by mistake. :)

Making this fit for newer chef versions is highly appreciated guys, thanks!

**Comment by CloCkWeRX** [comment]
Merge done, sing out if you want access
