### ISSUE TITLE
Chef 12.3.0 - undefined method `clear_sources' for Chef::Resource::RbenvGem

### ISSUE THREAD

**Issue by chourobin** [sous-chefs/ruby_rbenv#110]
For compatibility with Chef 12.3.0, I had to add a clear_sources attribute to resources/gem.rb.

https://github.com/chourobin/chef-rbenv

**Comment by vjm** [comment]
Any idea when this will get integrated?

**Comment by chourobin** [comment]
@vjm i think we're waiting for the author to assign a new maintainer.

**Comment by lucke84** [comment]
+1

**Comment by philicious** [comment]
I'm also facing this issue and would appreciate a fix

**Comment by volker-fr** [comment]
Is this chef-rbenv activly maintained or would it be saver to move to something else? A simple fix seems to be available for 20 days now.

**Comment by chourobin** [comment]
Doesn't look like this is actively maintained. The fix is pretty simple if you want to clone and install the gem spec locally.

**Comment by ianbrown78** [comment]
I have forked it to https://github.com/ianbrown78/chef-rbenv for the very
same reason.

**Comment by rusllonrails** [comment]
thanks @chourobin . You fork works perfect :+1: :beers:
