### ISSUE TITLE
Error executing action `install` on resource 'rbenv_gem

### ISSUE THREAD

**Issue by gibo** [sous-chefs/ruby_rbenv#111]
Using the following Vagrant file generates an error (using VBox)

Any ideas? Been banging my head against a brick wall for a whole day now.

```
chef.json = {
  rbenv: {
    user_installs: [{
      user: 'vagrant',
      rubies: ["2.1.2"],
      global: "2.1.2",
      gems: {
        "2.1.2" => [
          { name: "bundler" }
        ]
      }
    }]
  },
  mysql: {
    server_root_password: ''
  }
```

==> default: [2015-04-29T18:30:04+00:00] INFO: Forking chef instance to converge...
==> default: [2015-04-29T18:30:04+00:00] INFO: **\* Chef 12.3.0 ***
==> default: [2015-04-29T18:30:04+00:00] INFO: Chef-client pid: 5248
==> default: [2015-04-29T18:30:05+00:00] INFO: Setting the run_list to ["recipe[apt]", "recipe[nodejs]", "recipe[ruby_build]", "recipe[rbenv::user]", "recipe[rbenv::vagrant]", "recipe[vim]"] from CLI options
==> default: [2015-04-29T18:30:05+00:00] INFO: Run List is [recipe[apt], recipe[nodejs], recipe[ruby_build], recipe[rbenv::user], recipe[rbenv::vagrant], recipe[vim]]
==> default: [2015-04-29T18:30:05+00:00] INFO: Run List expands to [apt, nodejs, ruby_build, rbenv::user, rbenv::vagrant, vim]
==> default: [2015-04-29T18:30:05+00:00] INFO: Starting Chef Run for vagrant-ubuntu-trusty-64
==> default: [2015-04-29T18:30:05+00:00] INFO: Running start handlers
==> default: [2015-04-29T18:30:05+00:00] INFO: Start handlers complete.
==> default: [2015-04-29T18:30:07+00:00] INFO: execute[install-key 1655a0ab68576280] ran successfully
==> default: [2015-04-29T18:30:07+00:00] INFO: file[/etc/apt/sources.list.d/node.js.list] backed up to /var/chef/backup/etc/apt/sources.list.d/node.js.list.chef-20150429183007.081219
==> default: [2015-04-29T18:30:07+00:00] INFO: file[/etc/apt/sources.list.d/node.js.list] updated file contents /etc/apt/sources.list.d/node.js.list
==> default: [2015-04-29T18:30:07+00:00] INFO: file[/etc/apt/sources.list.d/node.js.list] sending delete action to file[/var/lib/apt/periodic/update-success-stamp](immediate)
==> default: [2015-04-29T18:30:07+00:00] INFO: file[/var/lib/apt/periodic/update-success-stamp] backed up to /var/chef/backup/var/lib/apt/periodic/update-success-stamp.chef-20150429183007.085984
==> default: [2015-04-29T18:30:07+00:00] INFO: file[/var/lib/apt/periodic/update-success-stamp] deleted file at /var/lib/apt/periodic/update-success-stamp
==> default: [2015-04-29T18:30:07+00:00] INFO: file[/etc/apt/sources.list.d/node.js.list] sending run action to execute[apt-get update](immediate)
==> default: [2015-04-29T18:30:09+00:00] INFO: execute[apt-get update] ran successfully
==> default: [2015-04-29T18:30:09+00:00] INFO: execute[apt-get update] sending touch action to file[/var/lib/apt/periodic/update-success-stamp](immediate)
==> default: [2015-04-29T18:30:09+00:00] INFO: file[/var/lib/apt/periodic/update-success-stamp] updated atime and mtime to 2015-04-29 18:30:09 +0000
==> default: [2015-04-29T18:30:09+00:00] INFO: execute[apt-get update] sending run action to execute[apt-cache gencaches](immediate)
==> default: [2015-04-29T18:30:11+00:00] INFO: execute[apt-cache gencaches] ran successfully
==> default: [2015-04-29T18:30:13+00:00] INFO: bash[Initialize rbenv (vagrant)] ran successfully
==> default: [2015-04-29T18:30:13+00:00] INFO: rbenv-post-init-vagrant
==> default: [2015-04-29T18:30:13+00:00] INFO: ruby_block[Add rbenv to PATH] called
==> default: 
==> default: ================================================================================
==> default: Error executing action `install` on resource 'rbenv_gem[2.1.2::bundler (vagrant)](vagrant)'
==> default: ================================================================================
==> default: 
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `clear_sources' for Chef::Resource::RbenvGem
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default: /tmp/vagrant-chef/a420bcca39f36a13667d14b8de0a0b71/cookbooks/rbenv/libraries/chef_provider_package_rbenvrubygems.rb:66:in`install_package'
==> default: 
==> default: Resource Declaration:
==> default: ---------------------
==> default: # In /tmp/vagrant-chef/a420bcca39f36a13667d14b8de0a0b71/cookbooks/rbenv/recipes/user.rb
==> default: 
==> default:  63:       rbenv_gem "#{gem['name']} (#{rbenv_user['user']})" do
==> default:  64:         package_name    gem['name']
==> default:  65:         user            rbenv_user['user']
==> default:  66:         root_path       rbenv_user['root_path'] if rbenv_user['root_path']
==> default:  67:         rbenv_version   rubie
==> default:  68: 
==> default:  69:         %w{version action options source}.each do |attr|
==> default:  70:           send(attr, gem[attr]) if gem[attr]
==> default:  71:         end
==> default:  72:       end
==> default:  73:     end
==> default: 
==> default: Compiled Resource:
==> default: ------------------
==> default: # Declared in /tmp/vagrant-chef/a420bcca39f36a13667d14b8de0a0b71/cookbooks/rbenv/recipes/user.rb:63:in `block (3 levels) in from_file'
==> default: 
==> default: rbenv_gem("bundler (vagrant)") do
==> default:   provider Chef::Provider::Package::RbenvRubygems
==> default:   action :install
==> default:   retries 0
==> default:   retry_delay 2
==> default:   default_guard_interpreter :default
==> default:   declared_type :rbenv_gem
==> default:   cookbook_name :rbenv
==> default:   recipe_name "user"
==> default:   package_name "bundler"
==> default:   user "vagrant"
==> default:   rbenv_version "2.1.2"
==> default:   gem_binary "export RBENV_ROOT=\"/home/vagrant/.rbenv\" && export PATH=\"$RBENV_ROOT/bin:$RBENV_ROOT/shims:$PATH\" && export RBENV_VERSION=\"2.1.2\" && $RBENV_ROOT/shims/gem"
==> default:   version "1.9.4"
==> default: end
==> default: 
==> default: [2015-04-29T18:30:17+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: [2015-04-29T18:30:17+00:00] ERROR: Running exception handlers
==> default: [2015-04-29T18:30:17+00:00] ERROR: Exception handlers complete
==> default: [2015-04-29T18:30:17+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2015-04-29T18:30:17+00:00] ERROR: rbenv_gem[2.1.2::bundler (vagrant)] (vagrant) (rbenv::user line 63) had an error: NoMethodError: undefined method`clear_sources' for Chef::Resource::RbenvGem
==> default: [2015-04-29T18:30:17+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

**Comment by vjm** [comment]
https://github.com/chourobin/chef-rbenv/commit/9fb5523956dd99b47db1c0199052bfd9b2f5b65c

**Comment by christhekeele** [comment]
Stuck on this as well.

**Comment by christhekeele** [comment]
It looks like `chef-rbenv` isn't compatible with version 12 of Chef and beyond. I was able to get it working with Chef 11.18.6, though.

**Comment by gibo** [comment]
Using this branch fixed it for me. 

https://github.com/chourobin/chef-rbenv/commit/9fb5523956dd99b47db1c0199052bfd9b2f5b65c

**Comment by christhekeele** [comment]
@gibo I'd say you should reopen this–it's an issue on this repo, even if it isn't on other forks.
