### ISSUE TITLE
Please add new mantainers

### ISSUE THREAD

**Issue by brauliobo** [sous-chefs/ruby_rbenv#112]
There is a lot of interest in this cookbook but not much feedback. Maybe a few more contributors might help!

**Comment by n8gard** [comment]
+1

**Comment by kizashi1122** [comment]
+1

**Comment by CloCkWeRX** [comment]
I'd be happy to maintain this - there's a few other contributors at work, and I'm just going through some of the commits in the graph to consolidate them into https://github.com/CloCkWeRX/chef-rbenv

**Comment by CloCkWeRX** [comment]
Dupe of #109

**Comment by josacar** [comment]
I can co-maintain it too

**Comment by fnichol** [comment]
@CloCkWeRX heya (and so long overdue, but…), should we make CloCkWeRX/chef-rbenv where this work is happening? I agree with everyone on this thread--more maintainers is the right idea.

So far, I'm seeing @CloCkWeRX and @josacar expressing interest--should we start there? I can grant commit to this repo in any case

**Comment by fnichol** [comment]
er, I also see https://github.com/chef-rbenv/chef-rbenv. Maybe moving my repo there could help? It would redirect all links so would preserve people's git remotes.

**Comment by fnichol** [comment]
Adding @josegonzalez to the list of volunteers, and very sorry about slow twitter responses. Kinda fell into a twitter vacation…

**Comment by fnichol** [comment]
Adding @scalp42 to the list (https://twitter.com/scalp42/status/618534955581202432), thanks for stepping up as well!

**Comment by nathwill** [comment]
:heart: thanks @fnichol! excited to see this :smiley:

**Comment by ianbrown78** [comment]
@fnichol I agree with the idea of moving to https://github.com/chef-rbenv/chef-rbenv. @CloCkWeRX has done a great job at merging the many changes from a great number of forks.

**Comment by brauliobo** [comment]
also agree to move to chef-rbenv/chef-rbenv, thanks @fnichol !

**Comment by notnmeyer** [comment]
YYYEEEEESSSSSSS

**Comment by fnichol** [comment]
Okay, we're set up with this repo moved into the [chef-rbenv](https://github.com/chef-rbenv) organization, which means that team permissions can carry us forward. Thank you all for your help here!

**Comment by josegonzalez** [comment]
Yayaya. @CloCkWeRX mind ensuring this repo is up to date with your repo?
