### ISSUE TITLE
0.8.0 version doesn't follow semantic versioning rules

### ISSUE THREAD

**Issue by cmparkinson** [sous-chefs/ruby_rbenv#118]
This project appears to be using semantic versioning, however it's not following the rules for version numbers.

Version 0.8.0 drops support for Chef 11, but only bumps the minor version number.  Since it is not backwards compatible, should it not be a major version increase?

**Comment by CloCkWeRX** [comment]
> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
