### ISSUE TITLE
Cookbook conflicts with another rbenv cookbook

### ISSUE THREAD

**Issue by petracvv** [sous-chefs/ruby_rbenv#125]
The rbenv cookbook listed on the [chef supermarket](https://supermarket.chef.io/cookbooks/rbenv) also has the rbenv name in its metadata. If we use other cookbooks that depend on that rbenv cookbook, we can get version conflicts that are hard to work around. 

Would you be willing to rename your cookbook to avoid version conflicts? Then you might be able to push this cookbook to the supermarket too.

**Comment by CloCkWeRX** [comment]
I wouldn't mind to be honest.

Thoughts on names?
- rbenv-more-useful-than-other-one
- i-cant-believe-its-not-rbenv
  ... something else?

**Comment by petracvv** [comment]
Honestly, I am pretty bad with naming things; I have a fork with everything renamed to rbenv2 to avoid the version conflict I was running into temporarily. Not sure is that is the best choice in this case. 

If I look on the supermarket, people have gone with stuff like chef_rvm or ruby_rvm since the base rvm name has been taken when putting their own version online.

**Comment by tas50** [comment]
Lets call it rbenv-ruby and get it released up on the community site asap.

**Comment by thenathanjones** [comment]
Yes. Please do. rbenv-ruby is fine, hell, chef-rbenv is also fine. This caused a bit of grief when we tried to use this with knife-solo because Berkshelf wasn't obeying the git source location when this was being pulled in as a transitive dependency.

**Comment by betocastelo** [comment]
rbenv2? rbenvjr? yarbenv (yet another rbenv)?

**Comment by troyready** [comment]
rbenv-ng?

**Comment by pkang** [comment]
Would love it if you would release your version of rbenv to supermarket! Any of the names suggested above are fine. Or how about just `fnichol-rbenv`? :)

**Comment by tas50** [comment]
I'm going to push this today as ruby-rbenv

**Comment by pkang** [comment]
:+1:  :clap:

**Comment by CloCkWeRX** [comment]
#126 mentions a few hiccups

**Comment by tas50** [comment]
The cookbook has been renamed and pushed to the supermarket.  No need for this now.
