### ISSUE TITLE
Cookbook Name Changed, Version not Incremented

### ISSUE THREAD

**Issue by ThatsNinja** [sous-chefs/ruby_rbenv#126]
Commit cd9adde, as discussed in https://github.com/chef-rbenv/ruby_rbenv/issues/125, changed the name of the cookbook without incrementing the version. This had the effect of breaking our dependent cookbooks in use in production.

Additionally, the name in the attributes didn't change along with the name of the cookbook.

For anyone Googling, this was the error output:

```
In your Berksfile, you have:
  cookbook 'rbenv'
But that cookbook is actually named 'ruby_rbenv'
This can cause potentially unwanted side-effects in the future.
NOTE: If you do not explicitly set the 'name' attribute in the metadata, the name of the directory will be used instead. This is often a cause of confusion for dependency solving.
```

Fix was to update the cookbook name in our Berksfile to `ruby_rbenv`.

**Comment by n8gard** [comment]
+1 for this; this rly hosed us. We have more errors we're efforting right now and will post shortly.

**Comment by CloCkWeRX** [comment]
#125

**Comment by tas50** [comment]
The version has not been incremented because the release is not done yet.  In general you shouldn't run off master from Github.  If you're using Berkshelf with a repo in Github the safe thing to do is to either run from a tag or from a known good SHA.  Pulling in master is asking for breaking changes since metadata only gets updated at the time of release.

**Comment by ThatsNinja** [comment]
Not to add to the burden you've generously shouldered here, but I'm afraid I must beg to differ. Breaking changes to a community cookbook should be pushed to a feature branch, and a PR opened against master when the FB is no longer breaking.

I submit that this is not a mere difference of opinion, and would enter into evidence every cookbook in the Supermarket. `cookbook 'name', '~> x.x.x'` is the convention.

Thanks for your time, @tas50.

**Comment by n8gard** [comment]
Agreed w/ @ThatsNinja. This is how every other community cookbook I've worked with is doing it. Right now, @tas50 , our implementing cookbooks are hosed because the version number wasn't incremented. What can we do to help? This is very impactful to us and is costing us.
