### ISSUE TITLE
uninitialized constant Chef::Resource::RbenvRehash

### ISSUE THREAD

**Issue by vais** [sous-chefs/ruby_rbenv#127]
```
==> default: NameError
==> default:
==> default:     ---------
==> default:     uninitialized constant Chef::Resource::RbenvRehash
==> default:
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /tmp/vagrant-chef/bbbe0ed4f7f9d1bdf623ed82c275c627/cookbooks/ruby_rbenv/libraries/chef_provider_package_rbenvrubygems.rb:85:in `rehash'
==> default:     /tmp/vagrant-chef/bbbe0ed4f7f9d1bdf623ed82c275c627/cookbooks/ruby_rbenv/libraries/chef_provider_package_rbenvrubygems.rb:67:in `install_package'
```

Searching the source for `RbenvRehash` confirms that it is not defined anywhere. Is there something I'm doing wrong, or is this a bug? Thanks!

**Comment by n8gard** [comment]
We are having this problem, also. We're dead in the water because the version number didn't get progressed and we can't point back to a good version of this cookbook.

**Comment by ThatsNinja** [comment]
Temporary workaround implemented by forking this repository and making a change similar to the following in my Berksfile:

```
cookbook 'rbenv',
      '= 0.8.0',
      :git => 'git@github.com:chef-rbenv/ruby_rbenv.git',
      :tag => 'v0.8.0'
```

**Comment by vais** [comment]
@tas50 since you made this change https://github.com/chef-rbenv/ruby_rbenv/commit/aed96b717cb9c8e3118583d8d37ffe6b9a69f604#diff-7c7d1552ffedf04f9d96b90becd7bda5R25, do you think reverting https://github.com/chef-rbenv/ruby_rbenv/commit/e6cc154979f98469240a45c735816c31020ad063 would fix this issue?

**UPDATE** Nope, tried it, and it did not.

**Comment by stevenolen** [comment]
+1 can this be pushed to the supermarket, the 1.0 supermarket version is broken!

**Comment by vais** [comment]
@stevenolen yep, the supermarket version 1.0 is broken - you get this error in the end even though everything actually worked.

**Comment by tas50** [comment]
Which version of chef-client are you using where 1.0 fails and can you share with me what resource you're using that causes the failure.  I'd like to reproduce this and make sure there's a test to prevent it from happening again.

**Comment by vais** [comment]
@tas50 hope this helps: https://gist.github.com/vais/1f3d0d884dc9e53da3d5 Provisioning with this setup fails with `uninitialized constant Chef::Resource::RbenvRehash` even though everything actually works. Thanks!

**Comment by MOZGIII** [comment]
Having this issue too with Chef 12.5.1 Omnibus package.
I'm only using attributes:

``` ruby
  # Vagrantfile
  config.vm.provision :chef_solo do |chef|
    chef.json = {
      rbenv: {
        user_installs: [
          {
            user: 'vagrant',
            rubies: [PROJECT_RUBY_VERSION],
            gems: {
              PROJECT_RUBY_VERSION => [
                { name: 'bundler' },
                { name: 'rake' }
              ]
            }
          }
        ]
      }
    }
    chef.run_list = %w{
      ruby_build
      ruby_rbenv::user
    }.map { |e| "recipe[#{e}]" }
  end
```
