### ISSUE TITLE
user recipe should pass timeout parameter to rbenv_gem

### ISSUE THREAD

**Issue by opsline-radek** [sous-chefs/ruby_rbenv#135]
When using `user` recipe and installing gems that take more than 300 seconds to compile, error is thrown (but chef run succeeds!).

It would be a good idea to specify timeout parameter in the attributes for each gem (just like version) and pass it to the resource. Right now it's ignored.

**Comment by damacus** [comment]
Hey @opsline-radek 

We've released a new version of this cookbook, could you check that the new version closes off your feature request? 


Thanks!
Dan
