### ISSUE TITLE
rbenv::system on mac os x

### ISSUE THREAD

**Issue by dei79** [sous-chefs/ruby_rbenv#14]
When I use "recipe[rbenv::system]" in my node.json file I get an error that the direcory /etc/profile.d does not exist (MAC does not support this out of the box). When I create the directory and add the functionality as describe behind the following link everything works great

http://hints.macworld.com/article.php?story=20011221192012445

**Comment by fnichol** [comment]
Hi there, do you think the above commit should address this adequately? I keep forgetting /etc/profile.d isn't on the Mac; I usually create it myself :)

**Comment by dei79** [comment]
My chef-solo based setup workflow for mac developer machines is implementing this. So I have no issues any more :-)
