### ISSUE TITLE
Uninstall ruby version?

### ISSUE THREAD

**Issue by aried3r** [sous-chefs/ruby_rbenv#142]
Is there a way to uninstall a ruby version installed via this cookbook?

**Comment by damacus** [comment]
Nothing right now. Just install and reinstall options on the Ruby resources: see https://github.com/sous-chefs/ruby_rbenv/blob/master/resources/ruby.rb#L22

If you need this feel free to drop a PR or open a ticket (though we're working through a backlog right now and it might be a little bit of time)
