### ISSUE TITLE
/etc/profile.d/rbenv.sh does not load on FreeBSD

### ISSUE THREAD

**Issue by sekrett** [sous-chefs/ruby_rbenv#144]
It can be manually included in `/etc/profile` for bash and in `/etc/zprofile` for zsh. By default FreeBSD does not load files from `profile.d`.

I took code from Debian and it works:

<pre>if [ -d /etc/profile.d ]; then
  for i in /etc/profile.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi</pre>

**Comment by damacus** [comment]
Right now we don't support FreeBSD.

If you'd like to add support for it. Please feel free to submit a PR!

**Comment by sekrett** [comment]
If you don't plan to support FreeBSD, please remove it from readme. It is clearly stated it was tested and runs without errors.

**Comment by damacus** [comment]
No problem. 

Any chance you can take a look at the new #169 PR, and give me some feedback on FreeBSD please?

**Comment by damacus** [comment]
We have two options here. 
Either 
- remove it
- find a way of automatically testing it in kitchen dokken (see .kitchen.dokken.yml for the complete list of platforms we regularly test on).

Obviously I'd prefer the second but I have no way right now of doing that.

**Comment by sekrett** [comment]
You just need to create a file `/etc/profile` on FreeBSD with content I already provided, it worked for me. But it is dangerous because a different profile may be created by someone else. Also writing tests is difficult. Personally I am trying to avoid FreeBSD, because it is different from Linux and requires additional steps in many places. Also I don't know why Chef is still not supporting FreeBSD 11, a lot of time have passed. Probably removing is better.

**Comment by damacus** [comment]
Thanks @sekrett feel free to submit a PR now the new custom resource PR is in! :) 

I've now removed FreeBSD from the testing matrix and supported platforms.
