### ISSUE TITLE
rbenv_ruby needs a umask option

### ISSUE THREAD

**Issue by volker-fr** [sous-chefs/ruby_rbenv#145]
`rbenv_ruby` gets executed with the `umask` setting of the user that executes `chef-client`. As result the global rbenv can end up with permissions that prevent regular users from accessing the folder.

As result `rbenv_ruby` needs a umask option.

**Comment by damacus** [comment]
Hi @volker-fr we would happily accept a PR for this issue! 

If you need help getting started please don't hesitate to get in contact.
