### ISSUE TITLE
set user_home_root for user not in /home/

### ISSUE THREAD

**Issue by munjeli** [sous-chefs/ruby_rbenv#151]
user install is failing for a user not in /home/ i.e. jenkins who lives at /var/lib/jenkins. I can think of a million workarounds for this, but what is the best way to set the attribute for the install of such a user?

**Comment by damacus** [comment]
Hi @munjeli 

We've released a new version of this cookbook.

The new resource finds the users home via built in Ruby method as you can see here: 

https://github.com/sous-chefs/ruby_rbenv/blob/master/resources/user_install.rb#L25

From what I can tell this should fix your issue. 

Happy bug hunting! 

Thanks!
Dan
