### ISSUE TITLE
[Question] Migrating from rbenv-cookbook

### ISSUE THREAD

**Issue by allaire** [sous-chefs/ruby_rbenv#152]
Anybody successfully migrated from https://github.com/RiotGamesCookbooks/rbenv-cookbook ?
This cookbook is more active, and would like to migrate our current stack to it. Wondering if there are any particularities I should be aware of.

Thanks

**Comment by damacus** [comment]
Nothing apart from we're in a the middle of a small rewrite to custom resources and we could do with more maintainers ;)
