### ISSUE TITLE
Chef 13 Deprecation - Resource cloning

### ISSUE THREAD

**Issue by damacus** [sous-chefs/ruby_rbenv#155]
Chef::Exceptions::DeprecatedFeatureError
           ----------------------------------------
           "Cloning resource attributes for yum_package[autoconf] from prior resource\nPrevious yum_package[autoconf]: /tmp/kitchen/cache/cookbooks/ruby_rbenv/providers/ruby.rb:112:in `block in install_ruby_dependencies'\nCurrent  yum_package[autoconf]: /tmp/kitchen/cache/cookbooks/ruby_rbenv/providers/ruby.rb:112:in `block in install_ruby_dependencies' (CHEF-3694)/tmp/kitchen/cache/cookbooks/ruby_rbenv/providers/ruby.rb:112:in `block in install_ruby_dependencies'.\nPlease see https://docs.chef.io/deprecations_resource_cloning.html for further details and information on how to correct this problem. at /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/formatters/doc.rb:419:in `deprecation'"

**Comment by tas50** [comment]
I'm no longer getting this with the latest release and we have deprecation warnings set to true
