### ISSUE TITLE
Source rbenv.sh template after installing it

### ISSUE THREAD

**Issue by Mic92** [sous-chefs/ruby_rbenv#16]
After rbenv is installed, it should be initialized to be used in the current provisioning.
In my case, I wanted to prepare my rails environment in vagrant, but my rbenv settings aren't applied at the first run of chef-solo.

**Comment by mlafeldt** [comment]
That's something I'm also struggling with.

`/etc/profile.d/rbenv.sh` will only be sourced after the next login (or Chef run), causing the first converge to fail.

Any workaround?

**Comment by mlafeldt** [comment]
Took me some time to figure this out, but here's a workaround to use rbenv immediately:

``` ruby
include_recipe 'ruby_build'
include_recipe 'rbenv::system'

# The rbenv cookbook installs /etc/profile.d/rbenv.sh which sets up the Ruby
# environment. But that file will only be sourced after the next login,
# causing the first converge to fail. With this workaround, rbenv will be
# available immediately.
ruby_block "Add rbenv to PATH" do
  block do
    rbenv_root = node['rbenv']['root_path']
    ENV['PATH'] = "#{rbenv_root}/shims:#{rbenv_root}/bin:#{ENV['PATH']}"
  end
end
```

**Comment by mlafeldt** [comment]
@fnichol Do you think that should be done by the cookbook itself? I do.

**Comment by pattersonc** [comment]
+1 on this issue. This issue makes the resources unusable.

**Comment by mlafeldt** [comment]
Btw, I've released a wrapper cookbook that fixes this issue: https://github.com/mlafeldt/ruby-cookbook

**Comment by pranas** [comment]
+1

**Comment by fnichol** [comment]
This would add the paths mentioned above into the Chef running process' `$PATH` environment variable, but keep in mind that ordering of resources would be important if you're counting on `rbenv` being loaded for shell out commands and the `rbenv_script` resource might be a better option to use which should properly load rbenv before executing the code.

With merging of #42, we should be able to close this out.
