### ISSUE TITLE
undefined method `definition' for Custom resource rbenv_ruby from cookbook rbenv

### ISSUE THREAD

**Issue by thiagoit** [sous-chefs/ruby_rbenv#166]
### Cookbook version
1.2.0

### Chef-client version
12.19.33

### Platform Details
Ubuntu 14.04 LTS
### Scenario:
Install ruby 2.2.7

### Steps to Reproduce:

include_recipe "ruby_build"
include_recipe "ruby_rbenv::system_instal"

rbenv_ruby "2.2.7"

### Expected Result:
Ruby 2.2.7 installed

### Actual Result:
Tried using system and system_uninstall and none is working.

Error message:

           undefined method `definition' for Custom resource rbenv_ruby from cookbook rbenv

**Comment by damacus** [comment]
This should get fixed as part of #169, thanks for highlighting it.

**Comment by damacus** [comment]
Hi @thiagoit ! 

We've released a new version of this cookbook, could you check that the new version closes off your bug? 

I'll be closing this issue in a weeks time. Happy bug hunting

Thanks!
Dan
