### ISSUE TITLE
rbenv_gem ignores rbenv_version

### ISSUE THREAD

**Issue by kpmueller** [sous-chefs/ruby_rbenv#173]
### Cookbook version
2.0.0

### Chef-client version
12.21.3

### Platform Details
ubuntu14.04

### Scenario:
trying to install a gem to a specific rbenv version

### Steps to Reproduce:

Given this code:

```
rbenv_gem gem_name do
  rbenv_version ruby_version
end
```

The gem is not being installed to the ruby_version version rbenv. I think the `rbenv_version` variable is ignored.

**Comment by damacus** [comment]
Hey @kpmuller thanks for the bug report. 

Can you get me the location of where it is installed please?

**Comment by damacus** [comment]
Fixed by #178

**Comment by kpmueller** [comment]
thanks @damacus !
