### ISSUE TITLE
rbenv_gem not installing defined version of the gem

### ISSUE THREAD

**Issue by jcputter** [sous-chefs/ruby_rbenv#177]
### Cookbook version
v2.0.1

### Chef-client version
Chef: 12.17.44
### Platform Details
Ubuntu 16.04 LTS

### Scenario:
```
rbenv_gem 'bundler' do
  version '1.13.6'
  user 'rails'
end
```

### Expected Result:
Should install bundler 1.13.6

### Actual Result:
Install bundler 1.15 (latest) and getting the following warning.

```* ruby_rbenv_gem[bundler] action install[2017-08-02T23:07:00+02:00] WARN: /var/chef/cache/cookbooks/ruby_rbenv/resources/gem.rb:48:in `block (2 levels) in class_from_file': property timeout is declared in both gem_package[bundler] and ruby_rbenv_gem[bundler] action :install. Use new_resource.timeout instead. At /var/chef/cache/cookbooks/ruby_rbenv/resources/gem.rb:48:in `block (2 levels) in class_from_file'
[2017-08-02T23:07:00+02:00] WARN: /var/chef/cache/cookbooks/ruby_rbenv/resources/gem.rb:49:in `block (2 levels) in class_from_file': property version is declared in both gem_package[bundler] and ruby_rbenv_gem[bundler] action :install. Use new_resource.version instead. At /var/chef/cache/cookbooks/ruby_rbenv/resources/gem.rb:49:in `block (2 levels) in class_from_file'```

**Comment by damacus** [comment]
yeah gimme 10 minutes I'm pretty sure i just got to the bottom of this "bug" (none of the gem stuff works happily right now)

**Comment by jcputter** [comment]
thanks!

**Comment by damacus** [comment]
I've fixed those warnings now too. 

I'll wait for travis to go green (or green on the ones whos package repos don't fail, or the compiles don't timeout... )
