### ISSUE TITLE
root_path does not appear to be defined?

### ISSUE THREAD

**Issue by saraid** [sous-chefs/ruby_rbenv#181]
### Cookbook version
`2.0.2`

### Chef-client version
`12.21.1-1`

### Platform Details
`ubuntu 14.04 x86_64`

### Scenario:
Installing Ruby 2.3.1

### Steps to Reproduce:
```ruby
node['rbenv']['rubies'].each do |the_ruby|
  rbenv_ruby the_ruby do
    action :install
  end

  rbenv_gem 'bundler' do
    rbenv_version the_ruby
  end
end
```

### Expected Result:
install ruby 2.3.1

### Actual Result:
```
[2017-08-04T00:34:51+00:00] INFO: Processing ruby_rbenv_ruby[2.3.1] action install (jenkins-workers::_ruby line 24)

================================================================================
Error executing action `install` on resource 'ruby_rbenv_ruby[2.3.1]'
================================================================================

TypeError
---------
no implicit conversion of nil into String

Cookbook Trace:
---------------
/tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/ruby_rbenv/resources/ruby.rb:74:in `join'
/tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/ruby_rbenv/resources/ruby.rb:74:in `ruby_installed?'
/tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/ruby_rbenv/resources/ruby.rb:56:in `block in class_from_file'

Resource Declaration:
---------------------
# In /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/jenkins-workers/recipes/_ruby.rb

24:   rbenv_ruby the_ruby do
25:     action :install
26:   end
27:

Compiled Resource:
------------------
# Declared in /tmp/packer-chef-solo/local-mode-cache/cache/cookbooks/jenkins-workers/recipes/_ruby.rb:24:in `block in from_file'

ruby_rbenv_ruby("2.3.1") do
action [:install]
retries 0
retry_delay 2
default_guard_interpreter :default
declared_type :rbenv_ruby
cookbook_name "jenkins-workers"
recipe_name "_ruby"
version "2.3.1"
rbenv_action "install"
end

System Info:
------------
chef_version=12.21.1
platform=ubuntu
platform_version=14.04
ruby=ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
program_name=chef-solo worker: ppid=2811;start=00:29:21;
executable=/opt/chef/bin/chef-solo
```

**Comment by damacus** [comment]
`root_path` is defined when you install rbenv via the system or user install resources. They setup the run state to that other resources can find it from a common place.

Right now it looks like you haven't told rbenv which type of install you want, a user or system based on. We don't assume/guess which you want by default. 

The system/user install resources setup rbenv in the relevant places, for rbenv_ruby to go ahead and install to that part of the filesystem. 

Both of install resources setup a root_path for either system, or the configured user. 

## System_install 
https://github.com/sous-chefs/ruby_rbenv/blob/master/resources/system_install.rb#L30

## user_install
https://github.com/sous-chefs/ruby_rbenv/blob/master/resources/user_install.rb#L35

## Root path helper
https://github.com/sous-chefs/ruby_rbenv/blob/master/libraries/chef_rbenv_script_helpers.rb#L47

**Comment by rambler** [comment]
I found this bug by running into the same issue. Perhaps it would be helpful to include an example of how to do common patterns with this cookbook.

**Comment by damacus** [comment]
@rambler do the tests in the test directory cover that well enough?

**Comment by damacus** [comment]
*Closing but feel free to continue to discuss!
