### ISSUE TITLE
Issues with v2 on CentOS7

### ISSUE THREAD

**Issue by stefhen** [sous-chefs/ruby_rbenv#182]
### Cookbook version
`2.0.3`

### Chef-client version
`chef_version=13.2.20`

### Platform Details
```
platform=centos
platform_version=7.3.1611
```

### Scenario:
- Installing any ruby versions fail.

### Steps to Reproduce:

I'm trying an extremely simple recipe with version `2.0.3` of the cookbook on centos7, but am getting errors similar to #174 and #175

My recipe simply consists of:

`rbenv_ruby '2.3.4'`

Any of the providers with v2 don't seem to work at all. I'm just trying this on a base centos7 kitchen image, does ruby-build need to also still be included and in the runlist, and all of the dependencies such as gcc, automake etc need to be installed prior to trying to use this cookbook to install a ruby version? I was thinking that might be the case and tried to use `rbenv_plugin` to install ruby-build first, but that also failed. Are there just some obvious dependencies not in the README that I'm just missing that are assumed to already be there?

Here is the full kitchen log if that helps:  https://gist.github.com/stefhen/4e2dd6fd19d54714a5fd7e41327eac99

**Comment by damacus** [comment]
Hi @stefhen 

what does your recipe look like? It should look similar to one of the test recipes in the cookbook.

**Comment by stefhen** [comment]
Hi @damacus,

Looks like I totally overlooked the examples and was just not properly doing `rbenv_system_install 'system'` properly before trying to install a specific ruby version like in one of the examples.

I've updated my cookbook to with this and things are working are intended. Sorry for wasting your time with this. Thanks!

**Comment by dan-jensen** [comment]
Hi @damacus,

I just ran into this same thing on CentOS 7.  Please correct me if I'm wrong, but after a bunch of experimentation it seems `rbenv_system_install` must appear at the top of every recipe, at least for CentOS.  Assuming that's the expected behavior, I don't think it's noted anywhere in the README or the examples in `test/`.  I think it might be fair to re-open this Issue at least until the documentation is updated.

**Comment by damacus** [comment]
Hi @dan-jensen we'd love a PR for anything, including docs that make this clearer.
