### ISSUE TITLE
Useless attributes in default.rb

### ISSUE THREAD

**Issue by gavvvr** [sous-chefs/ruby_rbenv#185]
Looks like the following attributes are useless but still exist in `default.rb`:

```
default['rbenv']['gems']      = {}
default['rbenv']['user_gems'] = {}
```

Btw how is it supposed to install a list of gems now?

**Comment by damacus** [comment]
Indeed they are useless! 

Fancy submitting a quick PR to remove these?

**Comment by damacus** [comment]
This is now in master. This will be included in the next feature release.
