### ISSUE TITLE
Can't install gems with user-installed rbenv

### ISSUE THREAD

**Issue by gavvvr** [sous-chefs/ruby_rbenv#186]
### Cookbook version
2.0.4

### Chef-client version
12.19.36

### Platform Details
Centos 6.7

### Scenario:
Install gems for Ruby with user (non-system) installed rbenv

### Steps to Reproduce:

I took [test recipe](https://github.com/sous-chefs/ruby_rbenv/blob/master/test/fixtures/cookbooks/test/recipes/gem.rb) and modified it to install rbenv in user-mode (non-system)

```ruby
user = vagrant

rbenv_user_install user

rbenv_ruby '2.4.1' do
  user user
end

rbenv_global '2.4.1' do
  user user
end

rbenv_gem 'mail' do
  version '2.6.5'
  options '--no-rdoc --no-ri'
  rbenv_version '2.4.1'
end

rbenv_gem 'mail' do
  version '2.6.6'
  rbenv_version '2.4.1'
  action :remove
end
```

### Expected Result:

Installed gems

### Actual Result:

> Errno::ENOENT
>  -------------
> No such file or directory - /versions/2.4.1/bin/gem

https://gist.github.com/gavvvr/a38fcfb8a9b9ab46d10ba06f97ff2cb8

**Comment by damacus** [comment]
If you're changing rbenv to a user install, you'll want to install rbenv under using the `rbenv_user_install ` resource, right now. It's not set a root path correctly as the `rbenv_user_install` resource hasn't set it.

**Comment by damacus** [comment]
Closing this now as we haven't seen any activity in 7+ days.

**Comment by HelioCampos** [comment]
Hi @damacus,

I'm having the same issue and i didn't understand quite right what you mean by "If you're changing rbenv to a user install, you'll want to install rbenv under using the rbenv_user_install resource, right now. It's not set a root path correctly as the rbenv_user_install resource hasn't set it."

This is example:
```ruby
app_name = 'my_app'
ruby_version = '2.4.1'
rbenv_user = 'vagrant'

rbenv_user_install rbenv_user
rbenv_global ruby_version do
  user rbenv_user
end

rbenv_gem 'bundler' do
  options '--no-rdoc --no-ri'
  rbenv_version ruby_version
end
```

Expected results: gem installed on `/home/vagrant/.rbenv/versions/2.4.1/ path`
Actual results: ```No such file or directory - /versions/2.4.1/bin/gem```

I tried to follow the test examples but I sill getting the `root_path` blank.
