### ISSUE TITLE
`rbenv_action` doing nothing

### ISSUE THREAD

**Issue by aried3r** [sous-chefs/ruby_rbenv#189]
### Cookbook version
2.0.4

### Chef-client version
13.4.24

### Platform Details
Ubuntu 16.04 LTS

### Scenario:
Remove older rubies

### Steps to Reproduce:
```Ruby
# Uninstall old rubies
OLD_RUBIES = %w[2.3.1 2.4.0 2.4.1].freeze
OLD_RUBIES.each do |old_ruby|
  rbenv_ruby old_ruby do
    rbenv_action 'uninstall'
  end
end
```

### Expected Result:
Rubies should get uninstalled.

### Actual Result:
They would get installed, weren't they already installed.

```
  * ruby_rbenv_ruby[2.3.1] action install
    * ruby_rbenv_plugin[ruby-build] action install
      * git[Install ruby-build plugin] action sync (up to date)
       (up to date)
    * apt_package[gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev, make] action install (up to date)
     (up to date)
  * ruby_rbenv_ruby[2.4.0] action install
    * ruby_rbenv_plugin[ruby-build] action install
      * git[Install ruby-build plugin] action sync (up to date)
       (up to date)
    * apt_package[gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev, make] action install (up to date)
     (up to date)
  * ruby_rbenv_ruby[2.4.1] action install
    * ruby_rbenv_plugin[ruby-build] action install
      * git[Install ruby-build plugin] action sync (up to date)
       (up to date)
    * apt_package[gcc, autoconf, bison, build-essential, libssl-dev, libyaml-dev, libreadline6-dev, zlib1g-dev, libncurses5-dev, libffi-dev, libgdbm3, libgdbm-dev, make] action install (up to date)
     (up to date)
```

**Comment by damacus** [comment]
What happens if you stipr this down to just:
```
rbenv_ruby '1.8.7' do
    rbenv_action 'uninstall'
  end
```

**Comment by atheiman** [comment]
its difficult to integration test undoing things with test-kitchen, you have to do multiple converges and point at a different .kitchen.yml each time.

I can whip something up to verify this, but it will take a bit of messing around.

**Comment by damacus** [comment]
@atheiman there's multi-stage kitchen runs coming. So that might be worth waiting for.

**Comment by atheiman** [comment]
@damacus do you have any real evidence multi-stage kitchen converges will happen? everytime i look at issues for it, it seems they are old and have no updates

**Comment by damacus** [comment]
It was brought up at the Chef Summit in London, and is part of their Kitchen 2.0 road map

**Comment by atheiman** [comment]
Neat, based on another issue I was just involved in, it sounds like clustered nodes will be more supported in 2.0 test-kitchen as well

These are two big things for tk, i hope they get implemented soon!

**Comment by damacus** [comment]
Any update on being able to reproduce this?

**Comment by aried3r** [comment]
Hey! Sorry for the long silence. I'll try to update to the latest version and report back next week.

**Comment by aried3r** [comment]
> What happens if you stipr this down to just:
> 
> rbenv_ruby '1.8.7' do
>     rbenv_action 'uninstall'
>   end

I tried

```Ruby
rbenv_ruby '2.3.1' do
  rbenv_action 'uninstall'
end
```

This was the output:
```
  * ruby_rbenv_ruby[2.3.1] action install
    * ruby_rbenv_plugin[ruby-build] action install
      * git[Install ruby-build plugin] action sync (up to date)
       (up to date)
```

So it tries to execute the default action (`install`) and then skips, because that's already installed.

Chef 14.1.2
Ruby 2.5.1
knife-solo 0.7.0.pre3
Ubuntu 16.04 LTS
ruby_rbenv 2.0.8

I'd love to give you something to reproduce it. Is there a template to reproduce bugs? A Vagrantfile or something similar?

**Comment by damacus** [comment]
This should be enough thank you! 

Just a simple recipe with the reproducible error. 

I'm going to put a test kitchen suite together to narrow this down them go from there

Thanks for taking the time to reproduce it again. 
Dan
