### ISSUE TITLE
Trying to install rbenv globally for a specific user then to install bundler

### ISSUE THREAD

**Issue by HelioCampos** [sous-chefs/ruby_rbenv#201]
### Cookbook version
2.0.6

### Chef-client version
12.18.31

### Platform Details
Amazon linux

### Scenario:
I want to install rbenv globally for a specific user then I want to install bundler.

### Steps to Reproduce:
Hi @damacus,

I'm having the same issue and i didn't understand quite right what you mean by "If you're changing rbenv to a user install, you'll want to install rbenv under using the rbenv_user_install resource, right now. It's not set a root path correctly as the rbenv_user_install resource hasn't set it."

I didn't understand your answer because in the Steps to reproduce the problem, the @gavvvr already told that he was using rbenv_user_install. Its in the 3rd line of the issue #186. 

I tried to follow the test examples but I sill getting the root_path blank.

```
app_name = 'my_app'
ruby_version = '2.4.1'
rbenv_user = 'vagrant'

rbenv_user_install rbenv_user
rbenv_global ruby_version do
  user rbenv_user
end

rbenv_gem 'bundler' do
  options '--no-rdoc --no-ri'
  rbenv_version ruby_version
end
```
### Expected Result:
```
Installed bundler gem into /home/vagrant/.rbenv/versions/2.4.1/...
```
### Actual Result:
```
No such file or directory - /versions/2.4.1/bin/gem
```

**Comment by damacus** [comment]
Almost got me for a moment there, you've not yet instructed rbenv to install a version. 

The rbenv_global resource is just is just doing  `rbenv global 2.4.1` on the command line (with some extra magic env stuff).

So you'll want to also do 
```
rbenv_ruby '2.4.1' do
    user rbenv_user 
end
```
To install your user ruby

**Comment by damacus** [comment]
>If you're changing rbenv to a user install, you'll want to install rbenv under using the rbenv_user_install resource, right now. It's not set a root path correctly as the rbenv_user_install resource hasn't set it

Looks like you're good with this one now? 
The `rbenv_user_install` resource installs rbenv to the users home directory, whereas rbenv_system_install installs it to a [system wide path](https://github.com/sous-chefs/ruby_rbenv/blob/master/resources/system_install.rb#L25). 

Subsequently, as you've done, when installing gems, or setting a global version, you'll want to specify a user to do this to, as there could be more than one install of rbenv on a machine.

**Comment by HelioCampos** [comment]
Hi @damacus ,

I still didn't get it how to make it right. This is what I'm trying now:
```ruby
  app_user = node['deployer']['user'] || 'root'
  app_name = node['app_name']
  rbenv_user = app_user
  ruby_version = node['deploy'][app_name]['ruby_version']    
  
  rbenv_user_install rbenv_user
  
  node['deploy'][app_name]['rbenv']['plugins'].each do |plugin|
    rbenv_plugin plugin['name'] do    
      git_url plugin['repository']
      git_ref plugin['ref']
      user rbenv_user
    end
  end
  
  rbenv_ruby ruby_version do
    user rbenv_user  
    verbose true
  end
  
  rbenv_global ruby_version do
    user rbenv_user
  end

  rbenv_gem 'bundler' do
    options '--no-rdoc --no-ri'   
    rbenv_version ruby_version
  end
```

**Comment by damacus** [comment]
Hey, 

so I doesn't look like there's much wrong with that install, what error are you having?

**Comment by HelioCampos** [comment]
To fix the problem I had to put the user like you said in the rbenv_gem method.
```
  app_user = node['deployer']['user'] || 'root'
  app_name = node['app_name']
  rbenv_user = app_user
  ruby_version = node['deploy'][app_name]['ruby_version']

  rbenv_user_install rbenv_user

  node['deploy'][app_name]['rbenv']['plugins'].each do |plugin|
    rbenv_plugin plugin['name'] do
      git_url plugin['repository']
      git_ref plugin['ref']
      user rbenv_user
    end 
  end 
  
  rbenv_ruby ruby_version do
    user rbenv_user
    verbose true
  end 

  rbenv_global ruby_version do
    user rbenv_user
  end 

  rbenv_gem 'bundler' do
    options '--no-rdoc --no-ri'
    rbenv_version ruby_version
    user rbenv_user
  end 
  ###############################
```

Best regards,

**Comment by damacus** [comment]
Cool. Thanks for updating!

Closing now.
