### ISSUE TITLE
missing files after version bump to 2.0.6

### ISSUE THREAD

**Issue by electriquo** [sous-chefs/ruby_rbenv#203]
### Cookbook version
2.0.6

### Scenario:
when upgrading from version 2.0.5 to 2.0.6, some files are missing. for instance, [`libraries/matchers.rb`](https://github.com/sous-chefs/ruby_rbenv/blob/v2.0.5/libraries/matchers.rb)

### Steps to Reproduce:
pull the latest version and run its chefspec examples.

### Expected Result:
chefspec matchers will not be missing.

### Actual Result:
chefspec matchers are missing.

speaking of chefspec matchers, maybe it is time to introduce the rest of the lwrp that this cookbook introduces into the chefspec matchers, for the ease of testing.

**Comment by damacus** [comment]
Matchers isn't required by later versions of chef client, chefdk etc.

Which versions of chefdk  chef client etc are you running?

**Comment by electriquo** [comment]
@damacus 
chef-client version 12.21.31
chefspec version 6.2.0

**Comment by damacus** [comment]
Yeah, I'd recommend running the test suite in chefdk, which will update a bunch of your testing tools and make the Matchers work.

You can pin the chef client to an older version should that ml be required too.

**Comment by damacus** [comment]
Going to go ahead and close this down. If it's still a problem, please drop us a line on #sous-chefs on http://community-slack.chef.io/
