### ISSUE TITLE
how to add a cookbook with no recipe to runlist in chef

### ISSUE THREAD

**Issue by flyingboy007** [sous-chefs/ruby_rbenv#204]
I am trying to learn `chef` and `cookbooks`. All `cookbooks` I seen have a `recipe`. But this one have no recipes in source code. So in that case how can I use this?

I tried adding `ruby_rbenv::system_install` to `runlist`. But showing `error` that it cant find `system_install` in cookbook `ruby_rbenv`. Similarly if I try adding just `ruby_rbenv` to `run_list` it shows cant find `default` recipe error.

Could some one tell me what am doing wrong here? 

Here is the chef repo am working with now [my repo][2]

I can make this work by wrapping this cookbook in a new wrapper cookbook. But is that how this should be done as there is no built in recipes?

  [2]: https://github.com/flyingboy007/basic-template

**Comment by damacus** [comment]
Hey @flyingboy007 this type of question is best asked on a mailing list or on the chef community slack.

The best place to start with this generally learn.chef.io

I'm going to close this down now. 
Thanks! 
Dan

**Comment by flyingboy007** [comment]
figured out already. Thanks.
