### ISSUE TITLE
rbenv_version not defaulted

### ISSUE THREAD

**Issue by askmike1** [sous-chefs/ruby_rbenv#210]
https://github.com/sous-chefs/ruby_rbenv/blob/ec4696937418535c37d4188e3a0ba9b515f70db5/resources/gem.rb#L36

Docs say that not including this should default to 'global', but following the code, this is never defaulted so the result turns out to be:
`No such file or directory - /usr/local/rbenv/versions//bin/gem`

**Comment by damacus** [comment]
Hi there! 

Thanks for taking the time to submit an issue. 

We would happily accept a pull request to resolve this issue. If you need help or guidance on submitting, please don't hesitate to ask! 

If you need help, or just wish to talk through issue please [join the Chef Community Slack](http://community-slack.chef.io/) and look for the #sous-chefs channel. 

Thanks,
Sous-Chefs

**Comment by damacus** [comment]
I'm going to change the property `version` to be required. 

This:
- simplifies making and using each ruby version
- provides an obvious interface for users rather than guessing which ruby version they are using.

**Comment by askmike1** [comment]
@damacus do you mean version or rbenv_version?

**Comment by damacus** [comment]
`rbenv_version` as per https://github.com/sous-chefs/ruby_rbenv/blob/2080227969b4e3b19486758141dfc3f910832917/resources/gem.rb#L36

**Comment by askmike1** [comment]
If you are going to do that then you need to ensure the documentation gets updated to specify that it will not default to global

**Comment by damacus** [comment]
Yeah checkout the pr. If stayed that in the pr too.

It'll be a minor version bump too as it's close to a breaking change in behaviour.

**Comment by damacus** [comment]
Closing as the documentation has now been updated. If the documentation is not clear, please feel free to submit a PR to clarify.
