### ISSUE TITLE
rbenv_script not working

### ISSUE THREAD

**Issue by iveskins** [sous-chefs/ruby_rbenv#222]
### Cookbook version
~> 2.0.9
### Chef-client version
14.1.12

### Platform Details
centos 6. vagrant VM

### Scenario:
I am trying to run "bundle install" via chef, in the correct rbenv context.

### Steps to Reproduce:
I made a wrapper cookbook.
metadata:
depends 'ruby_rbenv'
default.rb
rbenv_script 'bundle install' do
  rbenv_version node["agull_application"]["ruby_version"]
  cwd node["my_application"]["basedir"]
  user node["my_application"]["user"]
  code 'bundle package --all'
end
nodejson:
{ 
 "agull_application": {
    "basedir": "/home/vagrant/workspace/app",
    "user": "vagrant",
    "ruby_version": "2.2.2"
  }
}

### Expected Result:
I was expecting the command "bundle package --all" to run in folder "/home/vagrant/workspace/app" in ruby 2.2.2 context.

### Actual Result:
I got an error about "rbenv: command not found"

    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    bash[bundle install] (/home/vagrant/chef-solo/local-mode-cache/cache/cookbooks/ruby_rbenv/resources/script.rb line 39) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '127'
    ---- Begin output of "bash"  "/tmp/chef-script20180719-31539-lp7guz" ----
    STDOUT:
    STDERR: /tmp/chef-script20180719-31539-lp7guz: line 3: rbenv: command not found
    /tmp/chef-script20180719-31539-lp7guz: line 5: bundle: command not found
    ---- End output of "bash"  "/tmp/chef-script20180719-31539-lp7guz" ----
    Ran "bash"  "/tmp/chef-script20180719-31539-lp7guz" returned 127

Am I missing something about the use of script.
There also seems to be some problems with this code ..
ie. "path # Optional: User to run as" .. is commented as user .. and it takes an array?? and really the cwd option changed the path but isn't documented.

**Comment by iveskins** [comment]
looks like RBENV_ROOT is set to nil  
    bash("bundle install") do
        action [:run]
        default_guard_interpreter :default
        command nil
        backup 5
        interpreter "bash"
        declared_type :bash
        cookbook_name "application"
        user "vagrant"
        code "export RBENV_ROOT=\"\"\nexport PATH=\"${RBENV_ROOT}/bin:$PATH\"\neval \"$(rbenv init -)\"\nexport RBENV_VERSION=\"2.2.2\"\nbundle package --all\n"
        domain nil
        environment {"RBENV_ROOT"=>nil, "USER"=>"vagrant", "HOME"=>"/home/vagrant"}
        returns [0]
        live_stream false
        cwd "/home/vagrant/workspace/app"
      end

**Comment by iveskins** [comment]
Seems to work if I remove rbenv_version and user options.. but I would like to use those.

**Comment by iveskins** [comment]
after reading https://github.com/chef/chef/issues/2545 .. I see that the rbenv_script is a wrapper around chef bash .. so the environment option probably works the same way .. 
so I tried something like..
```
rbenv_script 'bundle install' do
  cwd node["my_application"]["basedir"]
  user node["my_application"]["user"]
  environment "PATH" => "/usr/local/rbenv/shims:/usr/local/rbenv/bin:#{ENV["PATH"]}"
  code "bundle package --all"
end
```
And It seems to be working.

**Comment by iveskins** [comment]
Maybe the readme should be updated to explain this.

**Comment by damacus** [comment]
Would you mind making a PR to make this clearer?

Thanks!

**Comment by iveskins** [comment]
Ok. 
I have made a PR "iveskins-rbenv_script-readme"
