### ISSUE TITLE
change user/group of a system install

### ISSUE THREAD

**Issue by darthdeus** [sous-chefs/ruby_rbenv#23]
Is there a way to specify which user or group should own the system wide install?

**Comment by fnichol** [comment]
At the moment the system install omits the `user` and `group` [attributes](https://github.com/fnichol/chef-rbenv/blob/master/libraries/chef_rbenv_recipe_helpers.rb#L64-L65), so ownership would be whatever user invoked Chef.

Would these be useful optional attributes in your use case?

**Comment by darthdeus** [comment]
Yes, that's exactly what I meant. At least for me it makes sense to specify who owns the install, without having to run chef under that user.

**Comment by CloCkWeRX** [comment]
If its really needed, chown away after deploy is my advice. Otherwise, PR's welcome.

**Comment by allaire** [comment]
@CloCkWeRX Would it makes sense to have something similar to https://github.com/RiotGamesCookbooks/rbenv-cookbook/blob/a7ae0eedbf678a8ac93456c325f9d69a8ac9d6f3/recipes/default.rb#L77-L79 ?

I think it's not a bad idea to not limit system install access to only one user
