### ISSUE TITLE
It should be possible to use the rbenv_script resource as a non-root user, with a system-wide installation

### ISSUE THREAD

**Issue by corporealfunk** [sous-chefs/ruby_rbenv#247]
### Cookbook version
2.1.2

### Chef-client version
14.x

### Platform Details
ubuntu-18.04 (bionic)
ubuntu-14.04 (trusty)

### Scenario:
I use the system-wide recipe to install rbenv and rubies.

I'd like to run an "rbenv-aware" command (even bundler!) as a non-root user and have those commands run as the non-root user, using the system-wide rbenv/ruby install.

This does not seem possible.

### Steps to Reproduce:

First, run the system-wide ruby recipe, and install a ruby. Then, in a recipe:

```ruby
rbenv_script "bundle" do
  user 'deploy'
  group 'deploy'
  cwd '/home/deploy/rails_app'
  code 'bundle'
end
```

It doesn't work, because by specifying a "user", I have also signaled to the cookbook that I have a user-rbenv installation, which I don't (see https://github.com/sous-chefs/ruby_rbenv/blob/9cf17d0e2cbfe8c7844dad265e8fb634b32d7f46/libraries/helpers.rb#L36).

I could do this, to signal that I have a system-wide installation (don't supply a user):

```ruby
rbenv_script "bundle" do
  group 'deploy'
  cwd '/home/deploy/rails_app'
  code 'bundle'
end
```

Bundle runs, but the vendor/bundle directory is owned by root. This is problematic.

### Expected Result:
I expect to be able to run an rbenv_script resource with a system-wide installation as a non-root user.

### Actual Result:
See above.

The "user" resource variable in the "rbenv_script" resource should not be "overloaded" to both signal a user-installation and also be used as the user for the underlying bash resource setup (https://github.com/sous-chefs/ruby_rbenv/blob/9cf17d0e2cbfe8c7844dad265e8fb634b32d7f46/resources/script.rb#L41). By overloading it in this way, we lose the ability to run an rbenv-aware script as a given user but with a system-wide install.

**Comment by damacus** [comment]
Welcome! Thanks for opening an issue. 

If you want to do this, then you'll need to explicitly set the root path property, so that it's not lazily evaluated and thus won't use that helper.

Let us know how that goes! 
Dan

**Comment by corporealfunk** [comment]
@damacus It doesn't seem like the "rbenv_script" resource accepts or uses a root_path property (it used to in previous versions of the cookbook). See the property definitions here:

https://github.com/sous-chefs/ruby_rbenv/blob/master/resources/script.rb

Essentially, the "script_code" helper is called, and tracing that through to here:

https://github.com/sous-chefs/ruby_rbenv/blob/9cf17d0e2cbfe8c7844dad265e8fb634b32d7f46/libraries/helpers.rb#L52

We can see that it calls the root_path helper without any check that there is a "new_resource.root_path" set. It don't think it would be hard to add a root_path property and make sure that it is overrides/trumps the root_path helper.

If that seems right to you, I could work on a pull request. (This would probably affect other resources as well, I'd have to trace that through).

**Comment by corporealfunk** [comment]
As far as I can tell a major refactor occurred at this commit:

https://github.com/sous-chefs/ruby_rbenv/commit/48e2be56c61c8816a51e2948fa9cbd6ec4dead08

which removed the ability to pass root_path to script.

note that the global resource still uses the root_path property and then lazy evaluates a default based on the user property:

https://github.com/sous-chefs/ruby_rbenv/blob/9cf17d0e2cbfe8c7844dad265e8fb634b32d7f46/resources/global.rb#L31

Perhaps this pattern could be replicated in other resources.

**Comment by damacus** [comment]
If you fancy opening a PR to fix this, it looks like a pretty easy one to implement! :)
