### ISSUE TITLE
https://github.com/sous-chefs/ruby_rbenv/pull/255 not merged properly ?

### ISSUE THREAD

**Issue by dormi** [sous-chefs/ruby_rbenv#266]
## :ghost: Brief Description

Some time ago I posted https://github.com/sous-chefs/ruby_rbenv/issues/254 and in theory it was fixed in https://github.com/sous-chefs/ruby_rbenv/pull/255

But I think something went wrong with the merging, because those changes are not in `master`

## :pancakes: Cookbook version

2.1.3 

## :tophat: Platform details

Debian 10.0

**Comment by JohnRoesler** [comment]
It looks like #255 was merged into the branch `debug-circleci-failures` and not master.

**Comment by dormi** [comment]
Exactly.

Can this be fixed @JohnRoesler @damacus ?
