### ISSUE TITLE
Per user global version

### ISSUE THREAD

**Issue by arjes** [sous-chefs/ruby_rbenv#27]
Let me know if I missed something.

I have 1.8.7 global. I would like to be able to set user specific global versions.

I am modifying chef-rbenv to accept a user_versions array and simply create the file .ruby-version in the user's root directory. I have tried a variety of configuration options but I am trying to avoid re-installing ruby for each user since space on these VMs is at a premium.

Did I miss something?

**Comment by CloCkWeRX** [comment]
Try current master and user_install of rbenv
