### ISSUE TITLE
Allow setting ruby-build environment variables

### ISSUE THREAD

**Issue by mperham** [sous-chefs/ruby_rbenv#32]
I'm adding this in chef-rbenv because it exposes the high-level LWRP to install rubies.

ruby-build has several nice env vars which can be used with some vagrant magic to avoid building the same ruby over and over:

https://github.com/sstephenson/ruby-build#special-environment-variables

It would nice to be able to set them since it looks like Chef explicitly sets the child command's environment so I don't believe I can just set `ENV[xxx] = '/foo/bar'` in my recipe.

**Comment by CloCkWeRX** [comment]
Supported via https://github.com/fnichol/chef-ruby_build
