### ISSUE TITLE
ruby_build not detected when using include_recipe

### ISSUE THREAD

**Issue by jimmycuadra** [sous-chefs/ruby_rbenv#35]
If you include and run the ruby_build cookbook by calling `include_recipe` from another cookbook, chef-rbenv fails to install Ruby using the rbenv::system recipe. It only works if you include ruby_build explicitly in the node's run list.

The problem seems to be the method `ruby_build_missing?` in the Ruby provider, which calls `node.recipe?`. Apparently this doesn't account for recipes included during the Chef run.

I'm using Chef 11.4.0.

**Comment by zhengjia** [comment]
Duplicate issue of https://github.com/fnichol/chef-rbenv/issues/31

**Comment by fnichol** [comment]
A lot has happened in the art of cookbook authoring since this cookbook was written. The big one is the wrapper cookbook idiom which relies a lot more on `include_recipe`. Totally right and #37 should get us back on track. Thank you all!

**Comment by hgilani** [comment]
@fnichol what is the recommended way to get fix for this using Berkshelf. I spent 2 days to figure solution for this issue and release v0.7.2 does not have this fix and many other changes since Dec 31 2012? Is pulling from master recommended with Berkshelf.
