### ISSUE TITLE
user_installs doesn't seem to work for all users.

### ISSUE THREAD

**Issue by stevenharman** [sous-chefs/ruby_rbenv#40]
We are using `chef-rbenv` to build a Vagrant box that is used for CI. Our `Vagrantfile` looks like this:

``` ruby
chef.json = {
  // ...
  :rbenv => {
      :user_installs => [
        { :user => 'jenkins' }
      ]
    },
}
```

In in our own cookbook we run the `jenkins::default` recipe, which creates a `jenkins` user on the system. We then run `rbenv::user_install` recipe which based on our configuration should install `rbenv` for the `jenkins` user.

However, when we `vagrant ssh` in and then `sudo su jenkins`, running `rbenv` results in `sh: rbenv: not found`.

We originally had two users in our `user_installs` list, the `jenkins` user and `vagrant` user. The `vagrant` user seemed to have rbenv installed correctly, while the `jenkins` user did not. We removed the `vagrant` user to limit moving parts as much as possible, but we've still had no luck.

Any ideas?

**Comment by mojotalantikite** [comment]
There is a shell script that gets dropped into /etc/profile.d/rbenv.sh that is responsible for setting up the proper sourcing of rbenv into your user's PATH. Scripts in /etc/profile.d/ get sourced when bash is run at login, but when you 'sudo su' you're just running a shell with a swapped user id. 

Try to 'sudo su' to your user and then run 'bash --login' to force a bash login, which should get that rbenv.sh script to run.
