### ISSUE TITLE
Chef::Exceptions::RecipeNotFound: could not find recipe user for cookbook rbenv

### ISSUE THREAD

**Issue by cr0cdev** [sous-chefs/ruby_rbenv#44]
Once I start to bootstrap a server it gives me a error:

could not find user recipe for cookbook rbenv

But the recipe is in the recipes folder. I can not get it to work even if I define the recipe in the role as well.

recipe rbenv
recipe rbenv::user

This is how I try to install user ruby in role:

  :rbenv => {
    :user_rubies => ['1.9.3-p392'],
    :global  => '1.9.3-p392',
    :user_installs => [
      {
        :user    => 'rubyuser',
        :global  => '1.9.3-p392',
        :rubies  => ['1.9.3-p392'],
        :gems    => {
          '1.9.3-p392' => [
            { :name => 'bundler' },
            { :name => 'capistrano' },
          ]
        }
      }
    ]
  },

I have tried to add user.rb recipe and user_install.rb recipe to rbenv cookbook in server /var/chef/cache/cookbooks/rbenv/recipes/ folder by hand, but that does not help me either. Theres nothing that needs rbenv before it runs the rbenv install. It gives me the error when it starts to install it.

Please help me.

**Comment by xmik** [comment]
If you use Berkshelf, you need to specify in your cookbook's Berksfile which rbenv cookbook you use. E.g.: 

``` ruby
cookbook "rbenv", github: "fnichol/chef-rbenv", ref: "0a3018634bafe58ad21c6ee271af015220e444b9"
```
