### ISSUE TITLE
Provider Check for ruby_build doesn't understand dependencies

### ISSUE THREAD

**Issue by Atalanta** [sous-chefs/ruby_rbenv#50]
The ruby provider makes a check:

```
def ruby_build_missing?
  ! node.recipe?("ruby_build")
end
```

This doesn't work in the case where ruby_build will be present because of a depends in a cookbook on the run list.  For example, a workstation cookbook which uses the rbenv::system recipe, with a default Ruby set, and a depends on both rbenv and ruby_build in the metadata.

**Comment by jondot** [comment]
+1 here. i'm just returning `false` there to work around it.

**Comment by clupprich** [comment]
+1 here. Using ruby_build's `ruby_build_ruby` instead.

**Comment by erithmetic** [comment]
+1 I'm using `include_recipe 'ruby_build'` which causes that check to fail.

**Comment by s2t2** [comment]
try including ruby_build in the run list:
`"run_list": [ "ruby_build", "recipe[main]" ]`

**Comment by pmcjury** [comment]
+1 Still an issue. I don't want to have to include ruby_build explicitly in my run list. Especially if I'm using an application cookbook pattern where I only include the application recipe.
Example:

`"run_list": [ "myface-prod" ]`

**Comment by troyready** [comment]
This is a duplicate of #35 and was fixed by b95dc000d83ac9c3e7bb612850c0bf7e859db5c3 . I believe it should be closed now
