### ISSUE TITLE
chef-rbenv and chef standard package

### ISSUE THREAD

**Issue by Govinda-Fichtner** [sous-chefs/ruby_rbenv#52]
Hello Guys,

currently I have the problem that I'd like to install passenger with the passenger_apache2 recipe. This recipe comes after the chef-rbenv recipe in my run_list. The problem now is that the passenger_apache2 recipe is using the standard 'package' resource to install gems... which install the passenger gem with the system ruby... Is there a smart way to make the standard 'package' aware of rbenv without modifying the passenger_apache2 recipe or rolling my own?

**Comment by CloCkWeRX** [comment]
Rolling your own ftw, though you probably did that some time ago...
