### ISSUE TITLE
rbenv_script does not apply the rbenv environment to not_if and only_if

### ISSUE THREAD

**Issue by jimmycuadra** [sous-chefs/ruby_rbenv#54]
`not_if` and `only_if` values inside an `rbenv_script` call should be wrapped in the rbenv environment just as `code` is. Consider this example (assuming a user installed Ruby for the user "vagrant"):

``` ruby
rbenv_script "bundle install" do
  code "bundle install --binstubs .bundle/bin"
  cwd "/vagrant"
  user "vagrant"
  group "vagrant"
  not_if "bundle check", cwd: "/vagrant", user: "vagrant"
end
```

This will raise an exception on subsequent runs because rbenv is not loaded for the `not_if` command and `bundle` will not be found.

**Comment by ka2n** [comment]
+1
rbenv_script is described as 'wrapper for the script resoruce'.

@jimmycuadra 
In your case, I think you should notifies other resource to this resource.

like

``` ruby
rbenv_script "bundle install" do
  code "bundle install --binstubs .bundle/bin"
  action :nothing
end

template "/vagrant/Gemfile" do
   source "Gemfile.erb"
   notifies :run, "rbenv_script[bundle install]", :delayed
end
```

Sorry, If I'm off the mark.
