### ISSUE TITLE
recipe[rbenv::system_install] not adding to .bashrc

### ISSUE THREAD

**Issue by axsuul** [sous-chefs/ruby_rbenv#6]
The recipe works good with installing ruby and setting the default ruby version, however, it doesn't append the `PATH` and `rbenv init` to my `/etc/bash.bashrc`. I'm still new to chef, so do I need to use a separate provider to do this? I see that there is a `script` provider that appears to do this.

I'm on `Ubuntu 11.10`

**Comment by fnichol** [comment]
The `rbenv::system_install` recipe should create a `/etc/profile.d/rbenv.sh` file which gets sourced from `/etc/profile` (https://github.com/fnichol/chef-rbenv/blob/master/recipes/system_install.rb#L29-33 and https://github.com/fnichol/chef-rbenv/blob/master/templates/default/rbenv.sh.erb). When you log in does it not have `rbenv` in your `PATH` with `which rbenv`?

**Comment by ghost** [comment]
Hi, 

The file you mentioned is indeed created and I can access rbenv after I log back in. Is there anyway to make the variables in this file available without logging back in? At the moment my cookbook installs rbenv using this cookbook and then goes on to execute other commands with require gems installed using rbenv, however as the PATH has not been amended I cannot see the install gems without calling source /etc/profile.d/rbenv.sh. It also means other cookbooks which rely on the version of ruby being used don't work i.e. passenger_apache2. 

Any help would be greatly appreciated. Thanks for the great cookbook.

**Comment by piousbox** [comment]
+1 this is a problem for me.

**Comment by fnichol** [comment]
Hi all, pull request #8 was merged in and should address this. If that's not the case, then please reopen. Thanks!
