### ISSUE TITLE
user installed gems are owned by root instead of user

### ISSUE THREAD

**Issue by dodizzle** [sous-chefs/ruby_rbenv#61]
When specifying a gem to be installed for a user the gem files are owned by root instead the user.

rbenv_gem "passenger-enterprise-server" do
  rbenv_version   "1.9.3p448"
  source "/tmp/passenger-enterprise-server-4.0.8.gem"
  user "app"
end

The passenger gem in this case should be owned by the "app" user but instead are owned by root.

**Comment by avit** [comment]
Also, global gems should probably be owned by `rbenv:rbenv` instead of `root:rbenv`
