### ISSUE TITLE
How to update rubygems under rbenv?

### ISSUE THREAD

**Issue by rb1980** [sous-chefs/ruby_rbenv#63]
I am trying to figure out how to keep rubygems updated in an manageable way with this cookbook.

I created the following recipe:

```
node.set["rubygems"]["version"] = "n.n.n"

bash "rubygems-update" do
  code <<-EOF
    gem update --system #{node["rubygems"]["version"]}
  EOF
end
```

Which works fine, but only updates the "system" ruby.
I guess I could then wrap that in a loop and iterate over the rbenv installed rubies, calling the version-specific gem binary.
But I am just wondering (hoping) if I am just missing something perhaps already built into the cookbook to do this in an easier way?

**Comment by CloCkWeRX** [comment]
I wouldn't recommend doing that. rbenv + ruby-build tend to handle all setup of rubygems.

For example; here's my local

```
s$ ls -alh ~/.rbenv/versions/2.1.6/bin/ | grep gem
-rwxr-xr-x 1 clockwerx clockwerx  575 Apr 15 13:38 gem
```

and rbenv points at it with a shim depending on the current ruby version

```
$ which gem
/home/clockwerx/.rbenv/shims/gem
```

If you really need to do it; use rbenv_script to run under a specific ruby. An example doing this with migrations/rake:

```
    rbenv_script "migrate_rails_database" do
      rbenv_version "1.8.7-p352"
      user          "deploy"
      group         "deploy"
      cwd           "/srv/webapp/current"
      code          %{rake RAILS_ENV=production db:migrate}
    end
```
