### ISSUE TITLE
Cannot find a resource for rbenv_root_path on ubuntu version 8.04

### ISSUE THREAD

**Issue by javierjeronimo** [sous-chefs/ruby_rbenv#66]
Hello, can someone help me with this error in Ubuntu 8.04 (chef-solo in vagrant):

NameError
Cannot find a resource for rbenv_root_path on ubuntu version 8.04
Cookbook Trace:
/tmp/vagrant-chef-1/chef-solo-1/cookbooks/rbenv/recipes/default.rb:22:in `from_file'

**Comment by bonzofenix** [comment]
I am having the same problem...

**Comment by meatherly** [comment]
Anyone figure out how to fix it yet?

**Comment by tily** [comment]
Maybe you should add line `depends 'rbenv'` to your `metadata.rb` of the cookbook that includes `rbenv::default` recipe.

**Comment by defrag** [comment]
@tily 's anwser is correct.

**Comment by fnichol** [comment]
Sounds like this is resolved by @tily's comment so I'll attempt to close this issue. If I'm incorrect, please reopen. Thanks!
