### ISSUE TITLE
Chef 11 upload error

### ISSUE THREAD

**Issue by jhmartin** [sous-chefs/ruby_rbenv#68]
When attempting to upload to a chef-11 server using ruby 1.9.3 / knife 11.8.0, I get the following errors:

FATAL: Cookbook file libraries/provider_rbenv_rubygems.rb has a ruby syntax error:
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/3f9366334334ffdb67f9f53491e49d32/rbenv/libraries/provider_rbenv_rubygems.rb:46: syntax error, unexpected ':', expecting ')'
FATAL:             options.merge!(env: {
FATAL:                                ^
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/3f9366334334ffdb67f9f53491e49d32/rbenv/libraries/provider_rbenv_rubygems.rb:50: syntax error, unexpected ')', expecting kEND
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/3f9366334334ffdb67f9f53491e49d32/rbenv/libraries/provider_rbenv_rubygems.rb:51: syntax error, unexpected tIDENTIFIER, expecting tAMPER
FATAL:             original_shell_out!(*args, options)
FATAL:                                               ^
FATAL: /Users/jhmartin/.librarian/tmp/chef/integration/knife/install/3f9366334334ffdb67f9f53491e49d32/rbenv/libraries/provider_rbenv_rubygems.rb:100: syntax error, unexpected $end, expecting kEND

**Comment by CloCkWeRX** [comment]
Closing, given https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/ - ruby 2.\* will avoid this problem
