### ISSUE TITLE
master is not compatible with chef-solo on vagrant

### ISSUE THREAD

**Issue by kevinrood** [sous-chefs/ruby_rbenv#69]
It looks like master is using code specific to Chef 11.  The version of chef-solo that ships with the default vagrant box (`precise64 (virtualbox)`) is Chef 10.

```
vagrant:~$ chef-solo --version
Chef: 10.14.2
```

Please reference this SO question which describes the issue: http://stackoverflow.com/questions/16855064/installing-ruby-1-9-3-on-vagrant-rbenv-nomethoderror-loaded-recipe

**Comment by adamgotterer** [comment]
Check out https://github.com/schisamo/vagrant-omnibus, it lets you install the latest version of chef

**Comment by CloCkWeRX** [comment]
Can you check this against current master; I believe this has been solved.
