### ISSUE TITLE
Breaks in Chef 10

### ISSUE THREAD

**Issue by mperham** [sous-chefs/ruby_rbenv#76]
We're using Chef 10 and "use_inline_provider" in /opt/chef-solo/current/cookbooks/rbenv/providers/global.rb throws:

```
NameError
---------
undefined local variable or method `use_inline_resources' for #<Class:0x00000002b06498>
```

**Comment by arthurnn** [comment]
same issue in here... any work-around?

**Comment by smasood** [comment]
+1
