### ISSUE TITLE
swap a lot of `bash /home/deploy/.rbenv/bin/rbenv init -` until all memory is used 

### ISSUE THREAD

**Issue by williamherry** [sous-chefs/ruby_rbenv#77]
I am try to use this cookbook to install ruby for non-root user and it stoped in 

```
Processing bash[Initialize rbenv (vagrant)] action run (rbenv::user_install line 83)
```

I login in to the vm, no memory to do anything, I try to figure out that's wrong but can't

**Comment by mbriggs** [comment]
same problem here, installing on precise64

**Comment by CloCkWeRX** [comment]
I'm going to suggest that it's more likely to fall on the ruby-build side of things than this cookbook specifically.
