### ISSUE TITLE
Please release new features as release

### ISSUE THREAD

**Issue by loupgaroublond** [sous-chefs/ruby_rbenv#85]
We run a 'strict' environment where /tmp is mounted with noexec, thus we need environment variable capabilities to modify where temporary files go during a ruby-build install run. We're using master for now, but isn't it time for  a release soon?

**Comment by razor-x** [comment]
+1
Any chance you can put this on the community site [supermarket](https://supermarket.getchef.com)?

I know there is an existing rbenv cookbook, but yours does a lot more.

**Comment by brauliobo** [comment]
+1 for a supermarket upload. @fnichol do you need help?

**Comment by CloCkWeRX** [comment]
https://github.com/chef-rbenv/chef-rbenv is my effort to fork this; I've added various fixes etc and am looking for other keen maintainers. @brauliobo if you felt like doing the prep work for a supermarket upload...

**Comment by CloCkWeRX** [comment]
There's a release/tag pushed for 0.7.3
