### ISSUE TITLE
Installing gems from a path does not work as documented

### ISSUE THREAD

**Issue by bklang** [sous-chefs/ruby_rbenv#86]
I'm trying to follow the documented `rbenv_gem` syntax for installing a gem from a path.  The example shows:

``` ruby
rbenv_gem "json" do
  rbenv_version   "ree-1.8.7-2011.03"
  source          "/tmp/json-1.5.1.gem"
  version         "1.5.1"
end
```

Using this syntax, I attempted to install a local gem called "demo_setup.gem" with this in my recipe:

``` ruby
rbenv_gem "demo_setup" do
   source "/srv/app/current/demo_setup.gem"
 end
```

However, this generates a broken "gem" command line that looks like this:

```
[2014-05-02T21:59:43+00:00] ERROR: rbenv_gem[demo_setup] (app_mojolingo_demo::app line 119) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of /opt/rbenv/versions/2.1.0/bin/gem install demo_setup -q --no-rdoc --no-ri  -v "0.0.1"   --source=/srv/app/current/demo_setup.gem --source=http://rubygems.org ----
STDOUT:
STDERR: ERROR:  While executing gem ... (OptionParser::InvalidArgument)
invalid argument: --source=/srv/app/current/demo_setup.gem
---- End output of /opt/rbenv/versions/2.1.0/bin/gem install demo_setup -q --no-rdoc --no-ri  -v "0.0.1"   --source=/srv/app/current/demo_setup.gem --source=http://rubygems.org ----
```

**Comment by benlangfeld** [comment]
`gem install` doesn't take a `--source` option. I'm not sure why this cookbook would ever have attempted to work as such. `gem install` simply takes a path to the `.gem` in place of the gem name.

**Comment by benlangfeld** [comment]
This option is added [in the Chef core ruby package provider](https://github.com/opscode/chef/blob/master/lib/chef/provider/package/rubygems.rb#L531-L542). I'm not currently sure why the regex match would be failing.

**Comment by benlangfeld** [comment]
So, after a little digging, I've figured out what the problem is. You are using the rbenv cookbook published on the community site, developed by RiotGames. Those guys [don't implement the source attribute properly](https://github.com/RiotGames/rbenv-cookbook/blob/00e50cb62f9ec4d825c6c516256bc381c7fa2e61/libraries/provider_rbenv_rubygems.rb#L84).
