### ISSUE TITLE
The Process stops during "script[~] action run"

### ISSUE THREAD

**Issue by emahub** [sous-chefs/ruby_rbenv#95]
During knife solo cook, the process becomes stop.
But the server machine seems to be installed with all ruby versions.
What is a cause? How do I investigate this behavior deeply?

OS: Amazon Linux AMI 2014.09.1 (HVM)

nodes/vagrant_work.json

<pre>    "run_list": [
        ...
        "ruby_build",
        "rbenv::system"
    ],
    "rbenv": {
        "user": "ec2-user",
        "rubies": ["2.1.5", "2.0.0-p598", "1.9.3-p551"],
        "global": "2.1.5"
    }</pre>

output.

<pre>      - install version 1.8.10-1.45.amzn1 of package subversion
[2014-11-16T08:35:35+00:00] WARN: Cloning resource attributes for package[autoconf] from prior resource (CHEF-3694)
[2014-11-16T08:35:35+00:00] WARN: Previous package[autoconf]: /home/ec2-user/chef-solo/cookbooks-2/rbenv/providers/ruby.rb:102:in `block in install_ruby_dependencies'
[2014-11-16T08:35:35+00:00] WARN: Current  package[autoconf]: /home/ec2-user/chef-solo/cookbooks-2/rbenv/providers/ruby.rb:102:in `block in install_ruby_dependencies'
    * package[autoconf] action installDEBUG: sudo -E -p 'knife sudo password: ' chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json stdout:  (up to date)
 (up to date)DEBUG: sudo -E -p 'knife sudo password: ' chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json stdout:

DEBUG: sudo -E -p 'knife sudo password: ' chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json stdout:
    DEBUG: sudo -E -p 'knife sudo password: ' chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json stdout: * rbenv_script[rbenv install 2.1.5 (system)] action run
* rbenv_script[rbenv install 2.1.5 (system)] action runDEBUG: sudo -E -p 'knife sudo password: ' chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json stdout:

DEBUG: sudo -E -p 'knife sudo password: ' chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json stdout:
      DEBUG: sudo -E -p 'knife sudo password: ' chef-solo -c ~/chef-solo/solo.rb -j ~/chef-solo/dna.json stdout: * script[rbenv install 2.1.5 (system)] action run
* script[rbenv install 2.1.5 (system)] action run</pre>

After "script[rbenv install 2.1.5 (system)] action run" messages, nothing is printed on a display.

**Comment by CloCkWeRX** [comment]
So, it looks like the user you are cooking with requires sudo with a password. I recommend cooking with a user that isn't in that situation.
If that's not the case, can you try this manually and try to pin down where you get up to vs chef.
