### ISSUE TITLE
Error executing action `run` on resource 'script[rbenv install 2.1.3 (vagrant)]'

### ISSUE THREAD

**Issue by alouanemed** [sous-chefs/ruby_rbenv#96]
I am installing a rails project using Vagrant && Chef, while provisioning the vagrant this error shows up !

==> default: BUILD FAILED (Ubuntu 14.04 using ruby-build 20141128)

==> default: =============================================================================
# ==> default: Error executing action `run` on resource 'script[rbenv install 2.1.3 (vagrant)]'

the full log : https://gist.github.com/AlouaneMed/8f6a47fe1313869148bd

**Comment by alouanemed** [comment]
up !

**Comment by n8gard** [comment]
I'm seeing this too.

**Comment by CloCkWeRX** [comment]
Will need to see contents of `/tmp/ruby-build.20141203135317.13736.log` or what happens if you manually try to build it.
