### ISSUE TITLE
Add an `rbenv_bin_path` attribute to `rbenv_script`

### ISSUE THREAD

**Issue by carsomyr** [sous-chefs/ruby_rbenv#97]
In [these lines](https://github.com/fnichol/chef-rbenv/blob/master/providers/script.rb#L55-56), `rbenv_script` assumes that `RBENV_ROOT` has a `bin` directory, which isn't always the case. For example, Homebrew will install rbenv itself into `/usr/local/opt/rbenv`, while the root directory containing shims and Rubies go into `/usr/local/var/rbenv`. Improper detection of the location of the `rbenv` executable will lead to [incorrectly generated shims](https://github.com/sstephenson/rbenv/blob/master/libexec/rbenv-rehash#L63-64) (notice that `RBENV_ROOT` is independent of the results of `command -v rbenv`).

**Comment by CloCkWeRX** [comment]
Happy if you want to shoot in a pull request for this.
